# Generated by Django 5.1.7 on 2025-04-11 07:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('face_match', models.BooleanField(blank=True, null=True)),
                ('id_document', models.ImageField(null=True, upload_to='documents/')),
                ('selfie_image', models.ImageField(null=True, upload_to='selfies/')),
            ],
        ),
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
