# Generated by Django 5.1.7 on 2025-04-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_verificationrequest_alter_election_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationRequest',
        ),
    ]
