# Generated by Django 5.1.7 on 2025-04-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_customuser_otp_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='already_voted',
            field=models.BooleanField(default=False),
        ),
    ]
